const AUTHENTICATION_STATES = {
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    AUTHENTICATING: 'AUTHENTICATING',
    AUTHENTICATED: 'AUTHENTICATED',
    UNAUTHENTICATING: 'UNAUTHENTICATING',
};

module.exports = {
    AUTHENTICATION_STATES,
};
