const AUTHENTICATION_STATES = {
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    AUTHENTICATING: 'AUTHENTICATING',
    AUTHENTICATED: 'AUTHENTICATED',
    UNAUTHENTICATING: 'UNAUTHENTICATING',
};

const ASSETS_STATES = {
    DOWNLOADING: 'DOWNLOADING',
    ACTIVATED: 'ACTIVATED',
    INSTALL_FAILED: 'INSTALL_FAILED',
};

module.exports = {
    AUTHENTICATION_STATES,
    ASSETS_STATES,
};
